name: ecoscrap_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Icons
  cupertino_icons: ^1.0.8

  # Google Maps (map UI)
  google_maps_flutter: ^2.6.0

  # User location (GPS)
  geolocator: ^13.0.1

  # Permissions (Android & iOS)
  permission_handler: ^11.3.1

  # Camera plugin
  camera: ^0.11.0+1

  # Optional: image picking from gallery
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
