name: ecoscrap_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

# Updated Firebase Versions
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10  

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  image_picker: ^1.1.1
  file_picker: ^8.0.0


  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/plastic_model.tflite
